/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Helpdesk Support Ticket Management System API
 * RESTful API for managing support tickets throughout their lifecycle.

**Key Features:**
- Create and manage support tickets
- Track ticket status with enforced state transitions
- Filter, sort, and paginate ticket lists
- No delete operations allowed

**Status Workflow:**
- `pending` → `accepted` | `rejected`
- `accepted` → `resolved` | `rejected`
- `resolved` → (final state)
- `rejected` → (final state)

 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';

const axiosInstance = axios.create({
  baseURL: '/api'
});

import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

/**
 * Current ticket status
 */
export type TicketStatus = typeof TicketStatus[keyof typeof TicketStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TicketStatus = {
  pending: 'pending',
  accepted: 'accepted',
  resolved: 'resolved',
  rejected: 'rejected',
} as const;

export interface Ticket {
  /** Unique ticket identifier (auto-generated) */
  id: string;
  /**
   * Ticket title
   * @maxLength 255
   */
  title: string;
  /**
   * Detailed description of the issue
   * @maxLength 2000
   */
  description: string;
  contact: Contact;
  /** Current ticket status */
  status: TicketStatus;
  /** Timestamp when ticket was created */
  createdAt: string;
  /** Timestamp of last update */
  updatedAt: string;
}

/**
 * Optional phone number
 * @pattern ^[+]?[\d\s\-()]{7,20}$
 */
export type ContactPhone = string | null;

export interface Contact {
  /** Contact person's name */
  name: string;
  /** Contact email address */
  email: string;
  /**
   * Optional phone number
   * @pattern ^[+]?[\d\s\-()]{7,20}$
   */
  phone?: ContactPhone;
}

/**
 * Optional phone number
 * @pattern ^[+]?[\d\s\-()]{7,20}$
 */
export type TicketCreateRequestContactPhone = string | null;

export type TicketCreateRequestContact = {
  /**
   * Contact name
   * @minLength 1
   */
  name: string;
  /** Contact email */
  email: string;
  /**
   * Optional phone number
   * @pattern ^[+]?[\d\s\-()]{7,20}$
   */
  phone?: TicketCreateRequestContactPhone;
};

export interface TicketCreateRequest {
  /**
   * Ticket title
   * @minLength 1
   * @maxLength 255
   */
  title: string;
  /**
   * Detailed description
   * @minLength 1
   * @maxLength 2000
   */
  description: string;
  contact: TicketCreateRequestContact;
}

/**
 * @pattern ^[+]?[\d\s\-()]{7,20}$
 */
export type TicketUpdateRequestContactPhone = string | null;

export type TicketUpdateRequestContact = {
  /** @minLength 1 */
  name?: string;
  email?: string;
  /** @pattern ^[+]?[\d\s\-()]{7,20}$ */
  phone?: TicketUpdateRequestContactPhone;
};

export interface TicketUpdateRequest {
  /**
   * Updated ticket title
   * @minLength 1
   * @maxLength 255
   */
  title?: string;
  /**
   * Updated description
   * @minLength 1
   * @maxLength 2000
   */
  description?: string;
  contact?: TicketUpdateRequestContact;
}

/**
 * Target status for the ticket. Server-side validation enforces allowed transitions:
- From `pending`: can transition to `accepted` or `rejected`
- From `accepted`: can transition to `resolved` or `rejected`
- From `resolved`: no transitions allowed (final state)
- From `rejected`: no transitions allowed (final state)

 */
export type TicketStatusUpdateRequestStatus = typeof TicketStatusUpdateRequestStatus[keyof typeof TicketStatusUpdateRequestStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TicketStatusUpdateRequestStatus = {
  pending: 'pending',
  accepted: 'accepted',
  resolved: 'resolved',
  rejected: 'rejected',
} as const;

export interface TicketStatusUpdateRequest {
  /** Target status for the ticket. Server-side validation enforces allowed transitions:
- From `pending`: can transition to `accepted` or `rejected`
- From `accepted`: can transition to `resolved` or `rejected`
- From `resolved`: no transitions allowed (final state)
- From `rejected`: no transitions allowed (final state)
 */
  status: TicketStatusUpdateRequestStatus;
}

export type TicketListResponsePagination = {
  /**
   * Current page number
   * @minimum 1
   */
  page: number;
  /**
   * Items per page
   * @minimum 1
   */
  limit: number;
  /**
   * Total number of tickets
   * @minimum 0
   */
  total: number;
  /**
   * Total number of pages
   * @minimum 0
   */
  totalPages: number;
  /** Whether there is a next page */
  hasNext: boolean;
  /** Whether there is a previous page */
  hasPrev: boolean;
};

export interface TicketListResponse {
  success: boolean;
  data: Ticket[];
  pagination: TicketListResponsePagination;
}

/**
 * Machine-readable error code
 */
export type ErrorResponseErrorCode = typeof ErrorResponseErrorCode[keyof typeof ErrorResponseErrorCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ErrorResponseErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  TICKET_NOT_FOUND: 'TICKET_NOT_FOUND',
  INVALID_STATUS: 'INVALID_STATUS',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  OPERATION_NOT_ALLOWED: 'OPERATION_NOT_ALLOWED',
} as const;

/**
 * Additional error details (optional)
 */
export type ErrorResponseDetails = { [key: string]: unknown };

export interface ErrorResponse {
  success: boolean;
  /** Machine-readable error code */
  errorCode: ErrorResponseErrorCode;
  /** Human-readable error message */
  message: string;
  /** Additional error details (optional) */
  details?: ErrorResponseDetails;
}

export type ListTicketsParams = {
/**
 * Filter by ticket status (supports multiple values). Can be sent as ?status=pending&status=accepted or ?status=pending,accepted
 */
status?: ListTicketsStatusItem[];
/**
 * Field to sort by
 */
sortBy?: ListTicketsSortBy;
/**
 * Sort direction
 */
sortOrder?: ListTicketsSortOrder;
/**
 * Page number (1-indexed)
 * @minimum 1
 */
page?: number;
/**
 * Number of items per page
 * @minimum 1
 * @maximum 100
 */
limit?: number;
};

export type ListTicketsStatusItem = typeof ListTicketsStatusItem[keyof typeof ListTicketsStatusItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListTicketsStatusItem = {
  pending: 'pending',
  accepted: 'accepted',
  resolved: 'resolved',
  rejected: 'rejected',
} as const;

export type ListTicketsSortBy = typeof ListTicketsSortBy[keyof typeof ListTicketsSortBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListTicketsSortBy = {
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;

export type ListTicketsSortOrder = typeof ListTicketsSortOrder[keyof typeof ListTicketsSortOrder];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListTicketsSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type CreateTicket201 = {
  success?: boolean;
  message?: string;
  data?: Ticket;
};

export type GetTicket200 = {
  success?: boolean;
  data?: Ticket;
};

export type UpdateTicket200 = {
  success?: boolean;
  message?: string;
  data?: Ticket;
};

export type UpdateTicketStatus200 = {
  success?: boolean;
  message?: string;
  data?: Ticket;
};

/**
 * Retrieve a list of tickets with optional filtering, sorting, and pagination
 * @summary List tickets
 */
export const listTickets = <TData = AxiosResponse<TicketListResponse>>(
    params?: ListTicketsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axiosInstance.get(
      `/tickets`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Create a new support ticket with auto-generated ID and pending status
 * @summary Create ticket
 */
export const createTicket = <TData = AxiosResponse<CreateTicket201>>(
    ticketCreateRequest: TicketCreateRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axiosInstance.post(
      `/tickets`,
      ticketCreateRequest,options
    );
  }

/**
 * Retrieve complete information for a specific ticket
 * @summary Get ticket details
 */
export const getTicket = <TData = AxiosResponse<GetTicket200>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axiosInstance.get(
      `/tickets/${id}`,options
    );
  }

/**
 * Update ticket title, description, or contact information.
Status cannot be updated through this endpoint (use PATCH /tickets/{id}/status instead).
The updatedAt timestamp is automatically updated.

 * @summary Update ticket information
 */
export const updateTicket = <TData = AxiosResponse<UpdateTicket200>>(
    id: string,
    ticketUpdateRequest: TicketUpdateRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axiosInstance.put(
      `/tickets/${id}`,
      ticketUpdateRequest,options
    );
  }

/**
 * Update ticket status with validation of allowed state transitions.

**Valid transitions (enforced server-side):**
- `pending` → `accepted` | `rejected`
- `accepted` → `resolved` | `rejected`
- `resolved` → (final state, no transitions allowed)
- `rejected` → (final state, no transitions allowed)

The updatedAt timestamp is automatically updated.

**Note:** While the schema accepts any valid status value, the server will validate
that the transition from the current status to the requested status is allowed.
Invalid transitions will result in a 422 Unprocessable Entity response.

 * @summary Update ticket status
 */
export const updateTicketStatus = <TData = AxiosResponse<UpdateTicketStatus200>>(
    id: string,
    ticketStatusUpdateRequest: TicketStatusUpdateRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axiosInstance.patch(
      `/tickets/${id}/status`,
      ticketStatusUpdateRequest,options
    );
  }

export type ListTicketsResult = AxiosResponse<TicketListResponse>
export type CreateTicketResult = AxiosResponse<CreateTicket201>
export type GetTicketResult = AxiosResponse<GetTicket200>
export type UpdateTicketResult = AxiosResponse<UpdateTicket200>
export type UpdateTicketStatusResult = AxiosResponse<UpdateTicketStatus200>